import MainLayout from "@/components/Layouts/MainLayout";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { ReduxProvider } from "./ReduxProvider";
import "./globals.css";
import "aos/dist/aos.css";
import { montserrat } from "@/assets/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${montserrat.variable}`}>
        <AppRouterCacheProvider>
          <ReduxProvider>
            <MainLayout>{children}</MainLayout>
          </ReduxProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
